### ISSUE TITLE
Image magnifier glass function 

### ISSUE THREAD

**Issue by simonedu** [gadenbuie/xaringanExtra#153] opened 2022-03-04 19:39 UTC
Thank your fantastic packages! I have learned a lot with your talks as well!

I was wondering if it were possible to add an image magnifier glass function to xaringanExtra. That would be awesome!

Cheers

**Comment by gadenbuie** [comment] 2022-06-03 20:41
Duplicate of #148

**Closed by gadenbuie** 2022-06-03 20:41 UTC
