### ISSUE TITLE
iframe-related links don't work when in a Tab in Panelset

### ISSUE THREAD

**Issue by howardm** [gadenbuie/xaringanExtra#88] opened 2021-02-15 17:11 UTC
Hi,

I've embedded a iframe containing an image viewer (Pacsbin) in a Tab in a Panelset (for a Distill article).  This is the code:

``````

```{r panelset, echo=FALSE}
xaringanExtra::use_panelset()
```

::::: {.panelset}

::: {.panel}

## Clinical Presentation {.panel-name}

This will be the History and Clinical Presentation.

:::

::: {.panel}

## Images {.panel-name}

````{=html}
<div style="text-align:center;">
<iframe src="https://player.vimeo.com/video/510041214" style="width: 480px; height: 512px; border: 0;" allowfullscreen></iframe>
</div>
````

:::

::: {.panel}

## Explanation of Findings {.panel-name}

This will be the explanation of the findings and an explication.

Testing Pacsbin viewer again:


```{=html}
<p>

  <div style="text-align:center;">
  <iframe class="pacsbin" preload=true
         id="vali"
         src="https://www.pacsbin.com/c/W1QLNa-iQS?s=5db79e00e55657647bcf5e1f&i=5db79e00e55657647bcf5e20&ww=3601&wc=2560&an=false&overlay=false&notes=false&header=false"
         style="width: 500px; height: 500px; border: 0;"></iframe>
         <ul class="list-inline list-pipe">
         <li><a class="pacsbin-link" href="#vali?s=0">PA Chest</a></li>
         <li><a class="pacsbin-link" href="#vali?s=1&scale=0.75">Axial CT</a></li>
         </ul>
         
  </div>
          
</p>

```


:::

:::::

``````

The iframe (with links) outside of the Panelset works, but the two associated links do not work when the iframe is in the Tab labelled Explanation of Findings , as indicated in this screenshot:

![Screen Shot 2021-02-15 at 9 43 02 AM](https://user-images.githubusercontent.com/6101226/107974844-6bc69d00-6f74-11eb-984d-6e2a4826aa06.jpg)

Can anyone determine why this is the case ?

Thanks!

Howard

**Comment by gadenbuie** [comment] 2021-02-15 17:57
Are those links supposed to control the content in the iframe?

**Comment by howardm** [comment] 2021-02-15 18:03
@gadenbuie 

Yes, those links control (invoke) the image data shown in the iframe -- two sets of images in this instance.

**Comment by gadenbuie** [comment] 2021-02-15 19:16
I think its most likely that this is an issue of pacsbin and how that web app is set up. I currently can't reproduce the above image; even with a plain `html_document` that includes _only_ the raw html block you described, I only see this in multiple browsers:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/5420529/107985563-4fd4f280-6f98-11eb-9ff7-b5040d704d7a.png">

**Comment by howardm** [comment] 2021-02-15 19:40
@gadenbuie 

Thanks a lot for trying!  I'll contact the developer of Pacsbin.

It is working on another "live " web page of mine (made with Hugo) : 

http://howardmann.us/post/strwebinarcases/

I wonder if it has something to do with the way the "non-live" web page is displayed in the browser as I work on it via RStudio.

Howard

**Comment by howardm** [comment] 2021-02-15 19:49
@gadenbuie 

Sorry! I forgot to mention that Pacsbin requires the use of pacsbin-related javascript files, which you don't have for testing.

Howard

**Comment by gadenbuie** [comment] 2021-02-16 01:08
I'm sorry that the panelset feature isn't working well with pacsbin. Unfortunately without the JavaScript resources it would be very hard for me to debug this. There are a few things that come to mind as to what might be the issue, but they all have to do with how the pacsbin app is setup and it's not likely that I could change panelset to fix it. It is somewhat unusual to have links in a parent page that communicate with content in an iframe, and I'm not very surprised that it doesn't work.

I'm going to close this issue for now but feel free to update or reopen if you have any insight or if you can come up with a reproducible example.

**Closed** 2021-02-16 01:08 UTC

**Comment by howardm** [comment] 2021-02-21 21:46
@gadenbuie A live test site is available now if you're inclined to view it: https://thoracicimaging.info/posts/2021-02-20-site-test/

The Pacsbin viewer-associated .js scripts are here: https://www.dropbox.com/sh/gdki8d1ddipk960/AAC-PnNTvnam5vTjWzaOkTrWa?dl=0

On the Test Site, the viewer and  links work when not in a Panelset; but not when in a Panelset. See the Panel titled: Explanation of Findings. I also often have to reload the Frame to make it work:

![Screen Shot 2021-02-21 at 2 40 02 PM](https://user-images.githubusercontent.com/6101226/108639681-07fc1280-7453-11eb-9aec-166b2dd86337.jpg)

Cheers.
